jwt:
  secret: ${JWT_SECRET:change-this-jwt-secret}
  expiration: ${JWT_EXPIRATION:86400000}

spring:
  jwt:
    secret: ${JWT_SECRET:change-this-jwt-secret}
    expiration: ${JWT_EXPIRATION:86400000}

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,env

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
