server:
  port: 8082

spring:
  datasource:
    url: ${APPLICATION_DB_URL:jdbc:mysql://localhost:3306/finflow_app_db?createDatabaseIfNotExist=true}
    username: ${APPLICATION_DB_USERNAME:root}
    password: ${APPLICATION_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
